[package]
name = "example_images_gui"
version.workspace = true
edition.workspace = true

[lib]
name = "gui"

[[bin]]
name = "ImagesTest"
path = "src/main.rs"

[dependencies]
egui_pysync = { workspace = true}

eframe = "0.32.0"
egui = { version = "0.32.0", features = ["rayon"] }
