[package]
name = "egui_states"
version.workspace = true
edition.workspace = true

[features]
client = ["dep:tokio-tungstenite", "tokio/rt-multi-thread", "tokio/net"]
client-wasm = [
    "dep:ws_stream_wasm",
    "dep:log",
    "dep:wasm-bindgen-futures",
    "tokio/macros",
]
build-script = []

[dependencies]
serde = { workspace = true }
egui = { version = ">= 0.33", features = ["rayon"] }
futures-util = { workspace = true }
parking_lot = { workspace = true }
bytes = { workspace = true }

egui_states_core = { workspace = true }
egui_states_macros = { workspace = true }

# client
tokio = { workspace = true, features = ["sync"] }
tokio-tungstenite = { workspace = true, optional = true }

# client-wasm
ws_stream_wasm = { version = "0.7", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
log = { version = "0.4", optional = true }
